//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.20 at 10:11:58 AM PST 
//


package com.redwood.rp.core.vo.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.redwood.rp.core.vo.generic.BaseAnalyticsVO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}createdDatetime"/>
 *         &lt;element ref="{}createdUser"/>
 *         &lt;element ref="{}lastUpdatedDatetime"/>
 *         &lt;element ref="{}lastUpdatedUser"/>
 *         &lt;element ref="{}correlationId"/>
 *         &lt;element ref="{}serviceName"/>
 *         &lt;element ref="{}serviceMethod"/>
 *         &lt;element ref="{}requestMessage"/>
 *         &lt;element ref="{}errorCode"/>
 *         &lt;element ref="{}errorMessage"/>
 *         &lt;element ref="{}severityCode"/>
 *         &lt;element ref="{}webUserId"/>
 *         &lt;element ref="{}webUsername"/>
 *         &lt;element ref="{}ipAddress"/>
 *         &lt;element ref="{}domainId"/>
 *         &lt;element ref="{}domainBuildId"/>
 *         &lt;element ref="{}emailAddress"/>
 *       &lt;/sequence>
 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createdDatetime",
    "createdUser",
    "lastUpdatedDatetime",
    "lastUpdatedUser",
    "correlationId",
    "serviceName",
    "serviceMethod",
    "requestMessage",
    "errorCode",
    "errorMessage",
    "severityCode",
    "webUserId",
    "webUsername",
    "ipAddress",
    "domainId",
    "domainBuildId",
    "emailAddress"
})
@XmlRootElement(name = "message")
public class ErrorLogVO extends BaseAnalyticsVO implements java.io.Serializable {

    @XmlElement(required = true)
    protected String createdDatetime;
    @XmlElement(required = true)
    protected String createdUser;
    @XmlElement(required = true)
    protected String lastUpdatedDatetime;
    @XmlElement(required = true)
    protected String lastUpdatedUser;
    @XmlElement(required = true)
    protected String correlationId;
    @XmlElement(required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected String serviceMethod;
    @XmlElement(required = true)
    protected String requestMessage;
    @XmlElement(required = true)
    protected String errorCode;
    @XmlElement(required = true)
    protected String errorMessage;
    @XmlElement(required = true)
    protected String severityCode;
    protected long webUserId;
    @XmlElement(required = true)
    protected String webUsername;
    @XmlElement(required = true)
    protected String ipAddress;
    protected int domainId;
    @XmlElement(required = true)
    protected String domainBuildId;
    @XmlElement(required = true)
    protected String emailAddress;
    @XmlAttribute(required = true)
    protected String source;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the createdDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * Sets the value of the createdDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDatetime(String value) {
        this.createdDatetime = value;
    }

    /**
     * Gets the value of the createdUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * Sets the value of the createdUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedUser(String value) {
        this.createdUser = value;
    }

    /**
     * Gets the value of the lastUpdatedDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedDatetime() {
        return lastUpdatedDatetime;
    }

    /**
     * Sets the value of the lastUpdatedDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedDatetime(String value) {
        this.lastUpdatedDatetime = value;
    }

    /**
     * Gets the value of the lastUpdatedUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedUser() {
        return lastUpdatedUser;
    }

    /**
     * Sets the value of the lastUpdatedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedUser(String value) {
        this.lastUpdatedUser = value;
    }

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceMethod() {
        return serviceMethod;
    }

    /**
     * Sets the value of the serviceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceMethod(String value) {
        this.serviceMethod = value;
    }

    /**
     * Gets the value of the requestMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMessage() {
        return requestMessage;
    }

    /**
     * Sets the value of the requestMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMessage(String value) {
        this.requestMessage = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the severityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverityCode() {
        return severityCode;
    }

    /**
     * Sets the value of the severityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverityCode(String value) {
        this.severityCode = value;
    }

    /**
     * Gets the value of the webUserId property.
     * 
     */
    public long getWebUserId() {
        return webUserId;
    }

    /**
     * Sets the value of the webUserId property.
     * 
     */
    public void setWebUserId(long value) {
        this.webUserId = value;
    }

    /**
     * Gets the value of the webUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebUsername() {
        return webUsername;
    }

    /**
     * Sets the value of the webUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebUsername(String value) {
        this.webUsername = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the domainId property.
     * 
     */
    public int getDomainId() {
        return domainId;
    }

    /**
     * Sets the value of the domainId property.
     * 
     */
    public void setDomainId(int value) {
        this.domainId = value;
    }

    /**
     * Gets the value of the domainBuildId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainBuildId() {
        return domainBuildId;
    }

    /**
     * Sets the value of the domainBuildId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainBuildId(String value) {
        this.domainBuildId = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
